name: test if we have SECRET_TOKEN

on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
    steps:
      - run: |
          echo "Did the update run?"
          [[ -z $GITHUB_TOKEN ]] && echo "I don't have GITHUB_TOKEN!" && exit 1
          exit 0

